name: Deploy page to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate Docs
        run: |
          npm i
          npm run build:storybook
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './storybook-static'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
